modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/legosteenjaap/DisableNightSkipping/issues"
license = "LGPL-3.0 License"

[[mods]]
modId = "disablenightskipping"
version = "${version}"
displayName = "DisableNightSkipping"
authors = "Legosteenjaap"
description = '''
This mod stops players from skipping the night by sleeping in a bed.
'''
logoFile = "icon.png"

[[dependencies.disablenightskipping]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disablenightskipping]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disablenightskipping]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"